# Generated by Django 3.1.1 on 2021-06-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('subjective', 'subjective'), ('objective', 'objective')], max_length=255)),
                ('choice1', models.CharField(blank=True, max_length=255, null=True)),
                ('choice2', models.CharField(blank=True, max_length=255, null=True)),
                ('choice3', models.CharField(blank=True, max_length=255, null=True)),
                ('choice4', models.CharField(blank=True, max_length=255, null=True)),
                ('subjective_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_choice', models.CharField(max_length=255)),
            ],
        ),
    ]
